name: Agência Sumô
description: "Portfólio de Wagner Beethoven, designer experiência na concepção, criação de artefatos digitas, entusiasta da acessibilidade e tecnologia assistivas"
slogan: Portfólio do designer Wagner Beethoven!
image-default: "img/image-default.jpg"

url: ""
baseurl: ""
permalink:  /:categories/:title.html

sass:
  sass_dir: scss
  style: compressed

about-name: Wagner Beethoven
about-title: UX/UI Designer
about-email: agenciasumo@gmail.com
about-phone: +55 81 986 496 080
about-neighborhood: Jardim Atlântico
about-city: Olinda
about-state: Pernambuco

collections:
  profile:
    output: true
